[2024-06-11T16:34:45.511+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: spotify_final_dag.create_table scheduled__2024-06-02T08:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
