[2024-06-12T07:14:29.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T07:14:29.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.create_table scheduled__2024-06-10T21:50:00+00:00 [queued]>
[2024-06-12T07:14:29.739+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.create_table scheduled__2024-06-10T21:50:00+00:00 [queued]>
[2024-06-12T07:14:29.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-12T07:14:29.848+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-10 21:50:00+00:00
[2024-06-12T07:14:29.978+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=420) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T07:14:29.988+0000] {standard_task_runner.py:63} INFO - Started process 448 to run task
[2024-06-12T07:14:30.079+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'create_table', 'scheduled__2024-06-10T21:50:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmpbtinmx0m']
[2024-06-12T07:14:30.081+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask create_table
[2024-06-12T07:14:30.210+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.create_table scheduled__2024-06-10T21:50:00+00:00 [running]> on host d317f063dba7
[2024-06-12T07:14:32.187+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T21:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T21:50:00+00:00'
[2024-06-12T07:14:32.385+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T07:14:32.386+0000] {sql.py:276} INFO - Executing: 
	CREATE TABLE IF NOT EXISTS my_played_tracks(
	song_name VARCHAR(200),
	artist_name VARCHAR(200),
	played_at VARCHAR(200),
	timestamp VARCHAR(200),
	CONSTRAINT primary_key_constraint PRIMARY KEY (played_at)
	)
        
[2024-06-12T07:14:32.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T07:14:32.525+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql` isn't defined
[2024-06-12T07:14:32.536+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=create_table, run_id=scheduled__2024-06-10T21:50:00+00:00, execution_date=20240610T215000, start_date=20240612T071429, end_date=20240612T071432
[2024-06-12T07:14:32.581+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task create_table (The conn_id `postgre_sql` isn't defined; 448)
[2024-06-12T07:14:32.633+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T07:14:32.659+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-12T07:14:32.702+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T07:14:32.710+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
