[2024-06-12T13:22:22.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T13:22:22.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.spotify_etl_final scheduled__2024-06-12T12:10:00+00:00 [queued]>
[2024-06-12T13:22:22.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.spotify_etl_final scheduled__2024-06-12T12:10:00+00:00 [queued]>
[2024-06-12T13:22:22.451+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-12T13:22:22.481+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spotify_etl_final> on 2024-06-12 12:10:00+00:00
[2024-06-12T13:22:22.497+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=53) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T13:22:22.502+0000] {standard_task_runner.py:63} INFO - Started process 55 to run task
[2024-06-12T13:22:22.501+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'spotify_etl_final', 'scheduled__2024-06-12T12:10:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmptnd6d93u']
[2024-06-12T13:22:22.503+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask spotify_etl_final
[2024-06-12T13:22:22.630+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.spotify_etl_final scheduled__2024-06-12T12:10:00+00:00 [running]> on host d317f063dba7
[2024-06-12T13:22:22.863+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='spotify_etl_final' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T12:10:00+00:00'
[2024-06-12T13:22:22.865+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T13:22:22.869+0000] {logging_mixin.py:188} INFO - ETL process started
[2024-06-12T13:22:23.280+0000] {spotify_final_dag.py:142} ERROR - Error during ETL process: 'items'
[2024-06-12T13:22:23.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T13:22:23.281+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_final_dag.py", line 136, in ETL
    df = spotify_etl()
         ^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_etl.py", line 83, in spotify_etl
    load_df = return_dataframe()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_etl.py", line 46, in return_dataframe
    for song in data["items"]:
                ~~~~^^^^^^^^^
KeyError: 'items'
[2024-06-12T13:22:23.296+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=spotify_etl_final, run_id=scheduled__2024-06-12T12:10:00+00:00, execution_date=20240612T121000, start_date=20240612T132222, end_date=20240612T132223
[2024-06-12T13:22:23.320+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 269 for task spotify_etl_final ('items'; 55)
[2024-06-12T13:22:23.331+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T13:22:23.365+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T13:22:23.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
